### ISSUE TITLE
Error when trying to connect to a host

### ISSUE THREAD

**Issue by Xquality** [Chykary/FizzySteamyMirror#5]
While connecting throws this error, hosting still works without a problem.

IndexOutOfRangeException: Index was outside the bounds of the array. Seems to be something to do with the byte array in line 74 of Common. Any ideas? :)

`IndexOutOfRangeException: Index was outside the bounds of the array.
Mirror.FizzySteam.Common.Send (Steamworks.CSteamID host, System.Byte[] msgBuffer, System.Int32 channel) (at Assets/FizzySteamyMirror/Common.cs:74)
Mirror.FizzySteam.Common.SendInternal (Steamworks.CSteamID target, Mirror.FizzySteam.Common+InternalMessages type) (at Assets/FizzySteamyMirror/Common.cs:73)
Mirror.FizzySteam.Client+<Connect>d__22.MoveNext () (at Assets/FizzySteamyMirror/Client.cs:61)
UnityEngine.Debug:LogException(Exception)
Mirror.NetworkClient:OnError(Exception) (at Assets/Mirror/Runtime/NetworkClient.cs:152)
UnityEngine.Events.UnityEvent`1:Invoke(Exception)
Mirror.FizzySteam.<>c__DisplayClass21_0:<CreateClient>b__3(Exception) (at Assets/FizzySteamyMirror/Client.cs:35)
Mirror.FizzySteam.<Connect>d__22:MoveNext() (at Assets/FizzySteamyMirror/Client.cs:79)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<Connect>d__22&)
Mirror.FizzySteam.Client:Connect(String)
Mirror.FizzySteam.Client:CreateClient(FizzySteamyMirror, String) (at Assets/FizzySteamyMirror/Client.cs:39)
Mirror.FizzySteam.FizzySteamyMirror:ClientConnect(String) (at Assets/FizzySteamyMirror/FizzySteamyMirror.cs:81)
Mirror.NetworkClient:Connect(String) (at Assets/Mirror/Runtime/NetworkClient.cs:86)
Mirror.NetworkManager:StartClient() (at Assets/Mirror/Runtime/NetworkManager.cs:390)
<JoinGame>d__20:MoveNext() (at Assets/Scripts/Networking/MyNetworkManager.cs:152)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
MainMenu:ButtonJoin() (at Assets/Scripts/Menus/MainMenu.cs:149)
UnityEngine.EventSystems.EventSystem:Update() (at C:/Program Files/Unity/Hub/Editor/2019.3.0f5/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)
`

Here is a screenshot of the console messages
https://i.imgur.com/oHWL5To.png

**Comment by IMerlin1009I** [comment]
I have exactly the same Error ^^ anyone knows a fix?

**Comment by Xquality** [comment]
I just rolled back to the previous working version for now. Waiting for a fix :)

**Comment by Chykary** [comment]
Hello Xquality and sorry for the late response, I didn't get a notification.

Does the problem still exist with 2.2.1?
